# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ThirdPartyAnimation_Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ThirdPartyAnimation_Swift

  pod 'Hero'
  target 'ThirdPartyAnimation_SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ThirdPartyAnimation_SwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
